import { useEffect, useState } from 'react';
import { MapContainer, TileLayer, Marker, Popup, Polyline } from 'react-leaflet';
import 'leaflet/dist/leaflet.css';
import { io } from 'socket.io-client';
import axios from 'axios';
import { Car, Navigation, AlertTriangle, CloudRain, Search, MapPin } from 'lucide-react';

const SOCKET_URL = 'http://localhost:5002';
const API_URL = 'http://localhost:5002/api/parking';

const cityCenter = [40.7128, -74.0060];

// Dummy route avoiding main congestion areas
const mockRouteCoords = [
  [40.7128, -74.0060],
  [40.7140, -74.0010],
  [40.7160, -73.9980],
  [40.7180, -73.9900]
];

const CitizenPortal = () => {
  const [parkingLots, setParkingLots] = useState([]);
  const [alerts, setAlerts] = useState([]);
  const [weatherRoute, setWeatherRoute] = useState('Clear');

  useEffect(() => {
    // Fetch initial parking data
    axios.get(API_URL).then(res => {
        if(res.data.success) setParkingLots(res.data.lots);
    }).catch(e => console.error(e));

    const socket = io(SOCKET_URL);
    
    socket.on('parkingUpdate', (updatedLot) => {
        setParkingLots(prev => prev.map(lot => 
            lot.parkingId === updatedLot.parkingId ? updatedLot : lot
        ));
    });

    socket.on('newAlert', (alertData) => {
        setAlerts(prev => [alertData, ...prev]);
    });

    socket.on('weatherShift', (data) => {
        setWeatherRoute(data.condition);
    });

    return () => socket.disconnect();
  }, []);

  return (
    <div className="min-h-screen bg-slate-50 relative flex flex-col">
      {/* Mobile-friendly Top Navigation */}
      <header className="bg-primary-600 text-white p-4 shadow-md z-10 sticky top-0 flex justify-between items-center">
        <div>
           <h1 className="text-xl font-bold tracking-tight">CityTraffic Portal</h1>
           <p className="text-xs opacity-80 flex items-center gap-1">
             <CloudRain className="w-3 h-3" /> {weatherRoute}
           </p>
        </div>
        <button className="bg-white/20 hover:bg-white/30 p-2 rounded-full transition-colors">
          <AlertTriangle className="w-5 h-5" />
        </button>
      </header>

      <div className="flex-1 relative z-0">
        <MapContainer center={cityCenter} zoom={13} style={{ height: '100%', width: '100%', minHeight: '50vh' }}>
          <TileLayer
            attribution='&copy; OpenStreetMap contributors'
            url="https://{s}.basemaps.cartocdn.com/light_all/{z}/{x}/{y}{r}.png" // Light mode for citizens
          />
          
          {/* Simulated Smart Route generated by backend AI avoiding congestion */}
          {activeRoute && (
              <Polyline positions={mockRouteCoords} color="#3b82f6" weight={5} opacity={0.8} />
          )}
          
          {/* Render Parking Lots */}
          {parkingLots.map((lot) => (
            <Marker key={lot.parkingId} position={[lot.coordinates.lat, lot.coordinates.lng]}>
              <Popup className="citizen-popup rounded-lg border-none shadow-lg">
                <div className="p-1">
                  <div className="font-bold text-slate-800 text-base mb-1">{lot.locationName}</div>
                  <div className="text-sm text-slate-600 mb-2 flex justify-between items-center bg-slate-100 p-2 rounded-md">
                    <span className="font-medium">Slots Available:</span>
                    <span className={`font-bold px-2 py-0.5 rounded ${lot.availableSlots < 10 ? 'bg-red-100 text-red-600' : 'bg-green-100 text-green-600'}`}>
                      {lot.availableSlots} / {lot.totalSlots}
                    </span>
                  </div>
                  <button onClick={() => setActiveRoute(true)} className="w-full mt-1 bg-primary-600 text-white py-2 rounded-md text-sm font-semibold hover:bg-primary-700 transition-colors flex items-center justify-center gap-2">
                    <Navigation className="w-4 h-4" /> Navigate (${(lot.pricePerHour || 5).toFixed(2)}/hr)
                  </button>
                </div>
              </Popup>
            </Marker>
          ))}
        </MapContainer>
        
        {/* Floating Quick Actions Panel */}
        <div className="absolute bottom-6 left-1/2 -translate-x-1/2 w-[90%] max-w-md pointer-events-none z-[1000]">
          <div className="bg-white/90 backdrop-blur-md rounded-2xl shadow-[0_8px_30px_rgb(0,0,0,0.12)] p-4 border border-slate-200 pointer-events-auto flex items-center gap-3">
             <div className="flex-1 bg-slate-100/80 p-3 rounded-xl flex items-center gap-2 cursor-text hover:bg-slate-200 transition-colors">
                 <Search className="w-4 h-4 text-primary-500" />
                 <span className="text-slate-500 text-sm font-medium">Search destination...</span>
             </div>
             <button onClick={() => setActiveRoute(!activeRoute)} className={`p-3 rounded-xl transition-colors shrink-0 shadow-lg ${activeRoute ? 'bg-accent-red hover:bg-red-600 text-white shadow-red-500/30' : 'bg-primary-500 hover:bg-primary-600 text-white shadow-primary-500/30'}`}>
                {activeRoute ? <MapPin className="w-5 h-5" /> : <Navigation className="w-5 h-5" />}
             </button>
          </div>
          
          {alerts.length > 0 && alerts[0].severity === 'Critical' && (
              <div className="mt-3 bg-red-500 text-white p-3 rounded-xl shadow-lg pointer-events-auto flex justify-between items-center animate-pulse border border-red-400">
                 <span className="text-sm font-medium flex items-center gap-2">
                    <AlertTriangle className="w-4 h-4 shrink-0" /> 
                    <span className="line-clamp-1 truncate">Avoid: {alerts[0].location}</span>
                 </span>
                 <button onClick={() => setAlerts(alerts.slice(1))} className="text-white/80 hover:text-white text-xs uppercase font-bold px-2 py-1 bg-black/20 rounded">Dismiss</button>
              </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default CitizenPortal;
